[tool.semantic_release]
version_variable = "app/__init__.py:__version__"
upload_to_pypi = false
upload_to_release=true
build_command = "python -m build"
branch = "main"
commit_author = "Tesista <bot@posgrado.com>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
major_tags = ["break", "feat!"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.pyright]
typeCheckingMode = "basic"

[tool.pylint.messages_control]
disable = ["C0115"]

[tool.pylint.format]
max-line-length = 200

[tool.pytest.ini_options]
env_files = ".test.env"
testpaths = ["tests"]